### ISSUE TITLE
Coding Style 

### ISSUE THREAD

**Issue by ekanna** [tristanwietsma/tabler#10]
Hi @tristanwietsma 

``` go
func (c *Column) Init(name, tag string) error {
    (*c).Name = name
```

Why do you use (*c).Name?
Why not c.Name ?

Just curious to know.

**Comment by tristanwietsma** [comment]
Just habit. Muscle memory, really. They are equivalent. In the current [feature branch](https://github.com/tristanwietsma/tabler/tree/breakup), I've changed it.

I guess I tend to register (mentally) that "*" means I'm modifying state, but you (and a few others who have pointed this out) are absolutely correct to point out it is unnecessary since Go automatically deref's the caller.

**Comment by ekanna** [comment]
Thank you. BTW tabler is really cool !!!

**Comment by tristanwietsma** [comment]
im going to keep this open till i merge the feature branch.
